version: '3.9'

services:
  frontend:
    build: ./services/frontend
    image: pypizza-frontend
    container_name: pypizza_frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    depends_on:
      - backend
  backend:
    build: ./services/backend
    image: pypizza-backend
    container_name: pypizza_backend
    volumes:
      - ./services/backend:/app'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host=0.0.0.0'
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pypizza
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pypizza

volumes:
  postgres_data: